spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  mvn:
    path match:
      matching-strategy: ant_part_matcher
  liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml
        enabled: true